[package]
name = "tests-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
header-plz = "0.0.30"
body-plz = "0.0.34"

# Compression
brotli = "8.0.0"
flate2 = "1.1.0"
zstd = "0.13.3"
bytes = { workspace = true }

decompression-plz = { path = ".." }
